const PDFDocument = require("pdfkit");
const {
  User,
  Medication,
  MedicationSchedule,
  DailyLog,
  Alert
} = require("../models");

async function generatePatientOnePager(userId) {
  const user = await User.findByPk(userId);
  if (!user) throw new Error("User not found");

  const medications = await Medication.findAll({
    where: { user_id: userId },
    include: [{ model: MedicationSchedule }]
  });

  const dailyLogs = await DailyLog.findAll({
    where: { user_id: userId },
    order: [["log_date", "DESC"]],
    limit: 14
  });

  const alerts = await Alert.findAll({
    where: { user_id: userId },
    order: [["created_at", "DESC"]],
    limit: 5
  });

  const fmt = (d) =>
    d ? new Date(d).toISOString().split("T")[0] : "—";

  // 🔑 IMPORTANT: wrap PDF generation in a Promise
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const chunks = [];

      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      /* ================= HEADER ================= */
      doc.fontSize(20).text("Patient Medication Safety Summary", {
        underline: true
      });
      doc.moveDown();

      doc.fontSize(12).text(`Patient Name: ${user.full_name}`);
      doc.text(`Phone: ${user.phone}`);
      doc.text(
        `Language: ${user.locale === "ml" ? "Malayalam" : "English"}`
      );
      doc.text(`Emergency Contact: ${user.emergency_contact}`);
      doc.moveDown();

      /* ================= MEDICATIONS ================= */
      doc.fontSize(16).text("Active Medications", { underline: true });
      doc.moveDown(0.5);

      if (!medications.length) {
        doc.text("No active medications.");
      } else {
        medications.forEach((m) => {
          doc.fontSize(12).text(
            `• ${m.drug_name_generic} (${m.drug_name_brand || "-"})`
          );

          if (!m.MedicationSchedules?.length) {
            doc.fontSize(10).text("   No schedules configured");
          } else {
            m.MedicationSchedules.forEach((s) => {
              doc.fontSize(10).text(
                `   - ${s.time_of_day} @ ${s.scheduled_time} | Dose: ${
                  s.dose
                } | ${s.before_food ? "Before food" : "After food"}`
              );
            });
          }
        });
      }

      doc.moveDown();

      /* ================= DAILY LOGS ================= */
      doc.fontSize(16).text("Last 14 Days Adherence", { underline: true });
      doc.moveDown(0.5);

      if (!dailyLogs.length) {
        doc.text("No adherence logs available.");
      } else {
        dailyLogs.forEach((l) => {
          doc.fontSize(11).text(
            `${fmt(l.log_date)} → ${l.status.toUpperCase()} | SE: ${
              Array.isArray(l.quick_se)
                ? l.quick_se.join(", ")
                : "None"
            } | Mood: ${l.mood_score ?? "—"} | Sleep: ${
              l.sleep_hours ?? "—"
            } hrs`
          );
        });
      }

      doc.moveDown();

      /* ================= ALERTS ================= */
      doc.fontSize(16).text("Recent Safety Alerts", { underline: true });
      doc.moveDown(0.5);

      if (!alerts.length) {
        doc.text("No alerts triggered.");
      } else {
        alerts.forEach((a) => {
          doc.fontSize(11).text(
            `${fmt(a.created_at)} – [${a.severity.toUpperCase()}] ${
              a.description
            } (Resolved: ${fmt(a.resolved_at)})`
          );
        });
      }

      /* ================= FOOTER ================= */
      doc.moveDown(2);
      doc.fontSize(10).text(
        "This report summarizes medication adherence, side effects, and safety alerts.\nGenerated by MediRaksha.",
        { align: "center" }
      );

      doc.end(); // 🔥 triggers stream completion
    } catch (err) {
      reject(err);
    }
  });
}

module.exports = { generatePatientOnePager };
